spring:
  datasource:
    username: admin
    password: adm1in@8042
    url: jdbc:postgresql://localhost:5432/apptdah
    driver-class-name: org.postgresql.Driver  # Driver JDBC do PostgreSQL

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Dialeto SQL do PostgreSQL
        format_sql: true
        hbm2ddl:
          auto: update  # Pode ser 'create', 'create-drop' ou 'update'

server:
  error:
    include-stacktrace: never

logging:
  file:
    name: logs/spring.log
  logback:
    rollingpolicy:
      total-size-cap: 100MB
      max-history: 30
      max-file-size: 10MB
      file-name-pattern: logs/archive/spring.%d{yyyy-MM-dd}.%i.log
  level:
    root: info

jwt:
  private-key: app.key
  public-key: app.pub
