name: Pipeline for App Tdah on Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin'
         java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: List target directory
        run: ls -l target/
        
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
         
      - name: Build Docker Image
        run: docker build -t jamesribeiro/api-apptdah .
        
      - name: Push image docker
        run: docker push jamesribeiro/api-apptdah

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull jamesribeiro/api-apptdah
        
      - name: Remove Docker Container
        run: docker rm -f api-apptdah
        
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} -e APP_PRIVATE_KEY='${{ secrets.APP_PRIVATE_KEY }}' -e APP_PUBLIC_KEY='${{ secrets.APP_PUBLIC_KEY }}' --network minha-rede --name api-apptdah jamesribeiro/api-apptdah        
        